# GoReleaser configuration for kyverno-mcp
# See https://goreleaser.com for full reference

version: 2

project_name: kyverno-mcp


builds:
  - id: kyverno-mcp
    main: .
    binary: kyverno-mcp
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w"

archives:
  - id: kyverno-mcp
    builds:
      - kyverno-mcp
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: desc

release:
  github:
    owner: "{{ .Env.GORELEASER_GITHUB_OWNER }}" # fallback to repo owner if unset
    name: "{{ .Env.GORELEASER_GITHUB_REPO }}"   # fallback to repo name if unset

