# .goreleaser.yaml – kyverno-mcp (v2 syntax)
version: 2
project_name: kyverno-mcp

before:
  hooks:
  - go mod tidy

builds:
- id: kyverno-mcp
  main: ./cmd
  binary: kyverno-mcp
  goos:   [linux, darwin, windows]
  goarch: [amd64, arm64]
  env:    [CGO_ENABLED=0]
  ldflags: ["-s -w"]

blobs:
- provider: s3
  region: us-east-2
  bucket: nirmata-downloads
  acl: private
  directory: kyverno-mcp/kyverno-mcp_{{ .Version }}
  disable: '{{ and (ne .Prerelease "") (not (contains .Prerelease "rc.")) }}'

signs:
- artifacts: all
  signature: ${artifact}.asc

archives:
  - ids: [kyverno-mcp]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

homebrew_casks:
  - name: kyverno-mcp
    homepage: https://docs.nirmata.io/kyverno-mcp/
    description: "Latest Kyverno MCP Server"
    repository:
      owner: nirmata
      name: homebrew-tap
      branch: main
      token: "{{ .Env.PAT_HOMEBREW_NCTL }}"
      pull_request:
        enabled: false
        base:
          owner: nirmata
          name: kyverno-mcp
          branch: main

  - name: "kyverno-mcp@{{ .Major }}.{{ .Minor }}"
    homepage: https://docs.nirmata.io/kyverno-mcp/
    description: "GA release {{ .Major }}.{{ .Minor }} of Kyverno MCP Server"
    skip_upload: '{{ ne .Prerelease "" }}'   
    conflicts:
      - formula: kyverno-mcp                  
    repository:
      owner: nirmata
      name: homebrew-tap
      branch: main
      token: "{{ .Env.PAT_HOMEBREW_NCTL }}"
      pull_request:
        enabled: false
        base:
          owner: nirmata
          name: kyverno-mcp
          branch: main

  - name: kyverno-mcp-rc
    homepage: https://docs.nirmata.io/kyverno-mcp/
    description: "Release-candidate builds of Kyverno MCP Server"
    skip_upload: '{{ not (contains .Prerelease "rc") }}'
    conflicts:
      - formula: kyverno-mcp
    repository:
      owner: nirmata
      name: homebrew-tap
      branch: main
      token: "{{ .Env.PAT_HOMEBREW_NCTL }}"
      pull_request:
        enabled: false
        base:
          owner: nirmata
          name: kyverno-mcp
          branch: main

release:
  prerelease: auto

source:
  enabled: false

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
    - '^config:'