apiVersion: v1
kind: Service
metadata:
  name: kyverno-mcp
  labels:
    app: kyverno-mcp
    app.kubernetes.io/name: kyverno-mcp
spec:
  selector:
    app: kyverno-mcp
  ports:
    - port: 443
      targetPort: 8000
  type: ClusterIP