name: Release

on:
  push:
    tags:
      - 'v*'
    branches:  # run on every commit so it appears
      - '**'
  workflow_dispatch: {}   # optional manual button

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.4
          check-latest: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
