name: Release

on:
  push:
    tags: ['v*']
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    outputs:
      version: ${{ steps.tag.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Extract tag
        id: tag
        run: echo "ver=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
      
      - name: Inspect OIDC token
        run: |
          raw=$(curl -s "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" \
                    -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")
            echo "$raw" | jq -R 'split(".") | .[1] | @base64d | fromjson'
      
      - name: Configure AWS credentials for S3 upload
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: false

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase:      ${{ secrets.GPG_PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOULD_UPDATE_BREW: "true"
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
  image:
    needs: goreleaser
    runs-on: blacksmith-2vcpu-ubuntu-2204
    permissions:
      id-token: write
      contents: read
      packages: write
    env:
      VERSION: ${{ needs.goreleaser.outputs.version }}
      KO_PLATFORMS:   linux/amd64,linux/arm64
      KO_DOCKER_REPO: ghcr.io/nirmata/kyverno-mcp
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ko CLI
        uses: ko-build/setup-ko@v0.6
      
      - name: Authenticate to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | 
          ko login ghcr.io --username ${{ github.actor }} 
          --password-stdin

      - name: Build + push multi-arch image with ko
        run: |
          ko build ./cmd \
            --platform="${KO_PLATFORMS}" \
            --tags "latest,${VERSION}" \
            --sbom=cyclonedx \
            --push

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign the pushed image (key-less OIDC workflow)
        run: |
          IMAGE="ghcr.io/${{ github.repository }}:${{ env.VERSION }}"
          cosign sign --yes "$IMAGE"